name: Renew No-IP domain

on:
  workflow_dispatch:
  schedule: # Twice a day
    - cron: '0 0 * * *'

env:
  token: ${{ secrets.TOKEN }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Install Checkout@v3
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: execute script # run main.py
        run: python noip-renew.py -e